#version: '3.8'
#
#services:
#  ecommerce-app:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080/auth
#    depends_on:
#      - mysql
#      - keycloak
#    networks:
#      - ecommerce-network
#
#  mysql:
#    image: mysql:8.0
#    environment:
#      MYSQL_ROOT_PASSWORD: rootpassword
#      MYSQL_DATABASE: ecommerce
#      MYSQL_USER: ecommerce
#      MYSQL_PASSWORD: ecommerce123
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#    networks:
#      - ecommerce-network
#
#  keycloak:
#    image: quay.io/keycloak/keycloak:22.0.5
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#      KC_DB: mysql
#      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
#      KC_DB_USERNAME: ecommerce
#      KC_DB_PASSWORD: ecommerce123
#    ports:
#      - "8081:8080"
#    command: start-dev
#    depends_on:
#      - mysql
#    networks:
#      - ecommerce-network
#
#volumes:
#  mysql_data:
#
#networks:
#  ecommerce-network:
#    driver: bridge
version: '3.8'

services:
  ecommerce-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080/auth
    depends_on:
      - mysql
      - keycloak
    networks:
      - ecommerce-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecommerce
      MYSQL_PASSWORD: ecommerce123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecommerce-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak?useSSL=false&allowPublicKeyRetrieval=true
      KC_DB_USERNAME: ecommerce
      KC_DB_PASSWORD: ecommerce123
    ports:
      - "8081:8080"
    command: start-dev
    depends_on:
      - mysql
    networks:
      - ecommerce-network
    volumes:
      - keycloak_data:/opt/keycloak/data   # ✅ persist Keycloak data here

volumes:
  mysql_data:
  keycloak_data:

networks:
  ecommerce-network:
    driver: bridge
